//LOCALHOST Employee Collection

### Get Employee list
GET http://localhost:3000/employee HTTP/1.1
### Get Employee by Id
GET http://localhost:3000/employee/6452e0c8e12 HTTP/1.1

### Create Employee
POST http://localhost:3000/employee HTTP/1.1
Content-Type: application/json

{
    "firstName": "Michael",
    "lastName": "Smith",
    "gender": "Male",
    "personalEmail": "michaelsmith@gmail.com",
    "jobTitle": "Produce Department Manager",
    "workEmail": "michaelsmith@grocerystore.com"
}

### Update a Employee
PUT http://localhost:3000/employee/645333785 HTTP/1.1
content-type: application/json

{
    "firstName": "Michael",
    "lastName": "Smith",
    "gender": "Male",
    "personalEmail": "michaelsmith@gmail.com",
    "jobTitle": "Store Manager",
    "workEmail": "michaelsmith@grocerystore.com"
}

### Delete Employee
DELETE http://localhost:3000/employee/645333785 HTTP/1.1




//LOCALHOST Planets Collection
### Get Planet list
GET http://localhost:3000/planets HTTP/1.1
### Get Planet by Id
GET http://localhost:3000/planets/6452e25ee12b6022b2bdcf59 HTTP/1.1

### Create Planet
POST http://localhost:3000/planets HTTP/1.1
Content-Type: application/json

{
    "planetName":"Lothal",
    "region":"Outer Rim",
    "sector":"Lothal Sector",
    "suns":"1",
    "moons":"2",
    "terrain":"Prairies"
}

### Update a Planet
PUT http://localhost:3000/planets/645333c05cb09e305b571c5d HTTP/1.1
content-type: application/json

{
    "planetName":"Lothal",
    "region":"Outer Rim",
    "sector":"Lothal Sector",
    "suns":"1",
    "moons":"2",
    "terrain":"Mountains"
}

### Delete Planet
DELETE http://localhost:3000/planets/6455bddf8a1a279f08700b20 HTTP/1.1

//PRODUCTION Deploy
### Get Character list
GET https://ryanalvordcit341.onrender.com/characters HTTP/1.1
### Get Character by Id
GET https://ryanalvordcit341.onrender.com/characters6452e0c8e12b6022b2bdcf54 HTTP/1.1

### Create Character
POST https://ryanalvordcit341.onrender.com/characters HTTP/1.1
Content-Type: application/json

{
    "firstName":"Darth",
    "lastName":"Vader",
    "gender":"Male",
    "race":"Human",
    "vehicle":"Advanced TIE Fighter",
    "affiliation":"Sith"
}

### Update a Character
PUT https://ryanalvordcit341.onrender.com/characters/645333785cb09e305b571c5c HTTP/1.1
content-type: application/json

{
    "firstName":"Darth",
    "lastName":"Vader",
    "gender":"Male",
    "race":"Human",
    "vehicle":"Advanced TIE Fighter",
    "affiliation":"Empire"
}

### Delete Character
DELETE https://ryanalvordcit341.onrender.com/characters/645333785cb09e305b571c5c HTTP/1.1

//LOCALHOST Planets Collection
### Get Planet list
GET https://ryanalvordcit341.onrender.com/planets HTTP/1.1
### Get Planet by Id
GET https://ryanalvordcit341.onrender.com/planets/6452e25ee12b6022b2bdcf59 HTTP/1.1

### Create Planet
POST https://ryanalvordcit341.onrender.com/planets HTTP/1.1
Content-Type: application/json

{
    "planetName":"Lothal",
    "region":"Outer Rim",
    "sector":"Lothal Sector",
    "suns":"1",
    "moons":"2",
    "terrain":"Prairies"
}

### Update a Planet
PUT https://ryanalvordcit341.onrender.com/planets/645333c05cb09e305b571c5d HTTP/1.1
content-type: application/json

{
    "planetName":"Lothal",
    "region":"Outer Rim",
    "sector":"Lothal Sector",
    "suns":"1",
    "moons":"2",
    "terrain":"Mountains"
}

### Delete Planet
DELETE https://ryanalvordcit341.onrender.com/planets/6455c05067c4ce408fe6e571 HTTP/1.1


{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}